<%--
    Document   : session_methods
    Created on : 26.07.2017, 12:33:39
    Author     : rhemmerling
--%>

<%@page import="java.util.Enumeration"%>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Some other Session Methods</title>
    </head>
    <body>
        <jsp:include page = "header.jsp"/>
        <h1>Some other Session Methods</h1>
    <li>session.getId(): <%= session.getId()%></li>
    <li>session.toString(): <%= session.toString()%></li>
    <li>session.getClass(): <%= session.getClass()%></li>
    <li>session.getCreationTime(): <%= session.getCreationTime()%></li>
    <li>session.getLastAccessedTime(): <%= session.getLastAccessedTime()%></li>
    <li>session.getMaxInactiveInterval(): <%= session.getMaxInactiveInterval()%></li>
    <li>session.getServletContext(): <%= session.getServletContext()%></li>
    <li>session.hashCode(): <%= session.hashCode()%></li>
    <li>session.invalidate(): <% // session.invalidate();%> 
        <ul>
            <li>This exception might be generated by some special session calls, if called subsequently "java.lang.IllegalStateException: isNew: Session already invalidated"</li>
            <li>We don't call the request here in this JSP demo</li>
            <li>"The method print(boolean) in the type JspWriter is not applicable for the arguments (void)"</li>
        </ul>
    <li>session.isNew(): <% session.isNew(); %> We don't call the request here in this JSP demo - "The method print(boolean) in the type JspWriter is not applicable for the arguments (void)"</li>
    <li>session.notify(): <% // application.notify(); %> We don't call the request here in this JSP demo - "The method print(boolean) in the type JspWriter is not applicable for the arguments (void)"</li>
    <li>session.notifyAll(): <% // application.notifyAll() %> We don't call the request here in this JSP demo - "The method print(boolean) in the type JspWriter is not applicable for the arguments (void)"</li>
    <li>session.setAttribute("MYATTRIBUTE4", "MyAttribute"): <% session.setAttribute("MYATTRIBUTE4", "MyAttribute"); %> - "The method print(boolean) in the type JspWriter is not applicable for the arguments (void)"</li>
    <li>session.getAttribute("MYATTRIBUTE4"): <%= session.getAttribute("MYATTRIBUTE4")%></li>
        <li>session.removeAttribute("MYATTRIBUTE4"): <% session.removeAttribute(
                "MYATTRIBUTE4");%> - "The method print(boolean) in the type JspWriter is not applicable for the arguments (void)"</li>
    <li>session.getAttribute("MYATTRIBUTE4"): <%= session.getAttribute("MYATTRIBUTE4")%></li>
    <li>session.setMaxInactiveInterval(1000): <% session.setMaxInactiveInterval(1000); %> - "The method print(boolean) in the type JspWriter is not applicable for the arguments (void)"</li>
    <li>session.wait(); session.wait(1); session.wait(1,1):
        <% if (false) {
                try {
                    session.wait();
                    session.wait(1);
                    session.wait(1, 1);
                } catch (InterruptedException e) {
                    out.println("<I>InterruptedException</I>");
                }
            }%> - We don't call the request here in this JSP demo - "The method print(boolean) in the type JspWriter is not applicable for the arguments (void)"</li>
</body>
</html>
